# LLM Configuration
llm:
  development:
    provider: "gemini"
    model: "gemini-2.5-flash"
    temperature: 0.1
    max_tokens: 4096
  
  production:
    provider: "gemini"
    model: "gemini-2.5-flash"
    temperature: 0.1
    max_tokens: 4096

# API Configuration
apis:
  arxiv:
    base_url: "http://export.arxiv.org/api/query"
    max_results: 100
    delay: 3  # seconds between requests
  
  openalex:
    base_url: "https://api.openalex.org/works"
    rate_limit: 10  # requests per second (OpenAlex allows up to 10)
    timeout: 30
    user_agent: "AcademicResearchAssistant/1.0 (mailto:rmoazhassan555@gmail.com)"
  
  crossref:
    base_url: "https://api.crossref.org/works"
    mailto: "rmoazhassan555@gmail.com"  # Required for CrossRef politeness policy
    rate_limit: 1  # Be conservative with rate limiting
    timeout: 30

# Storage Configuration
storage:
  database_path: "data/research.db"
  papers_dir: "data/papers"
  cache_dir: "data/cache"
  outputs_dir: "data/outputs"

# Agent Configuration
agents:
  max_retries: 3
  timeout: 300  # seconds
  verbose: true

# Research Configuration
research:
  max_papers_default: 50
  min_confidence_threshold: 0.5
  
# Logging Configuration
logging:
  level: "INFO"
  file: "logs/research_assistant.log"
  max_file_size: "10MB"
  backup_count: 5