# LLM Configuration
llm:
  development:
    provider: "gemini"
    model: "gemini-2.5-flash"
    temperature: 0.1
    max_tokens: 4096
  
  production:
    provider: "gemini"
    model: "gemini-2.5-flash"
    temperature: 0.1
    max_tokens: 4096

# API Configuration - FIXED
apis:
  arxiv:
    base_url: "http://export.arxiv.org/api/query"
    max_results: 50  # Reduced from 100 for better performance
    delay: 3  # seconds between requests
    timeout: 60  # Added timeout
  
  openalex:
    base_url: "https://api.openalex.org/works"
    mailto: "rmoazhassan555@gmail.com"  # FIXED: Added explicit mailto for OpenAlex
    rate_limit: 5  # Reduced from 10 to be more conservative
    timeout: 30
    user_agent: "AcademicResearchAssistant/1.0 (mailto:rmoazhassan555@gmail.com)"
    max_results: 200  # Added max results limit
  
  crossref:
    base_url: "https://api.crossref.org/works"
    mailto: "rmoazhassan555@gmail.com"  # Required for CrossRef politeness policy
    rate_limit: 1  # Be conservative with rate limiting
    timeout: 30
    max_results: 100  # Added max results limit
    rate_limit_delay: 1.5
    max_results_per_query: 25  # Reduced to prevent overload
    use_select_parameter: false 


# Storage Configuration
storage:
  database_path: "data/research.db"
  papers_dir: "data/papers"
  cache_dir: "data/cache"
  outputs_dir: "data/outputs"
  batch_size: 20  # Added for batch operations

# Agent Configuration - ENHANCED
agents:
  max_retries: 2  # Reduced from 3
  timeout: 120  # Increased from 300 seconds for individual operations
  verbose: true
  max_concurrent_searches: 2  # Added limit for parallel searches
  search_timeout: 60  # Added search timeout

# Research Configuration - ENHANCED
research:
  max_papers_per_search: 50
  default_search_providers: ["openalex", "crossref", "semantic_scholar"]
  concurrent_requests: 2
  search_timeout: 120
  note_confidence_threshold: 0.5
  theme_frequency_threshold: 3
  
# Logging Configuration
logging:
  level: "INFO"
  file_enabled: true
  file_path: "logs/research_assistant.log"
  console_enabled: true
  structured_logging: true
  max_file_size: 10485760  # 10MB in bytes
  backup_count: 5

# Performance Configuration - NEW
performance:
  enable_parallel_search: false  # Default to sequential for stability
  max_concurrent_requests: 2
  request_timeout: 30
  retry_attempts: 2
  backoff_factor: 2
  batch_processing: true